version: '3.7'

services:
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:12.0.4
    volumes:
      - ./keycloak/realm/:/keycloak/
      - ./keycloak/my_theme/:/opt/jboss/keycloak/themes/my_theme/
    ports:
       - "8080:8080"
    environment:
      - DB_VENDOR=mariadb
      - DB_ADDR=mariadb
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - KEYCLOAK_USER=keycloak_admin
      - KEYCLOAK_PASSWORD=keycloak_admin
      - KEYCLOAK_IMPORT=/keycloak/my_realm.json -Dkeycloak.profile.feature.scripts=enabled -Dkeycloak.profile.feature.upload_scripts=enabled
    restart: always
    depends_on:
      - mariadb
      - ldap
      - ldapinit
  mariadb:
    container_name: mariadb
    image: mariadb:10.5
    #volumes:
    #  - ./mariadb/:/var/lib/mysql/
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb_admin
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=keycloak
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "--silent"]
  ldap:
    container_name: ldap
    image: 389ds/dirsrv:latest
    expose:
      - "3636"
    environment:
      - DS_DM_PASSWORD=ldap_admin
    shm_size: 256m
  ldapinit:
    container_name: ldapinit
    build: ./ldapinit
    volumes:
      - ./ldapinit/ldif/:/ldif/
    environment:
      - DS_DM_PASSWORD=ldap_admin
      - DS_BASE_DN=dc=example,dc=org
    depends_on:
      - ldap
  react:
    container_name: react
    build: ./react
    volumes:
      - ./react/src/:/usr/src/app/src/
      - ./react/public/:/usr/src/app/public/
    ports:
      - "3000:3000"
  nodejs:
    container_name: nodejs
    build: ./nodejs
    volumes:
      - ./nodejs/src/:/usr/src/app/src/
      - ./nodejs/keycloak.json:/usr/src/app/keycloak.json
    ports:
      - "8888:8888"
